export const WS_CONNECTION_START_COMMON = 'WS_CONNECTION_START_COMMON';
export const WS_CONNECTION_CLOSE_COMMON = 'WS_CONNECTION_START_COMMON';
export const WS_CONNECTION_SUCCESS_COMMON = 'WS_CONNECTION_SUCCESS_COMMON';
export const WS_CONNECTION_ERROR_COMMON = 'WS_CONNECTION_ERROR_COMMON';
export const WS_CONNECTION_CLOSED_COMMON = 'WS_CONNECTION_CLOSED_COMMON';
export const WS_CONNECTION_START_PROFILE = 'WS_CONNECTION_START_PROFILE';
export const WS_CONNECTION_CLOSE_PROFILE = 'WS_CONNECTION_START_PROFILE';
export const WS_CONNECTION_SUCCESS_PROFILE = 'WS_CONNECTION_SUCCESS_PROFILE';
export const WS_CONNECTION_ERROR_PROFILE = 'WS_CONNECTION_ERROR_PROFILE';
export const WS_CONNECTION_CLOSED_PROFILE = 'WS_CONNECTION_CLOSED_PROFILE';
export const WS_GET_COMMON_ORDERS = 'WS_GET_COMMON_ORDERS';
export const WS_GET_PROFILE_ORDERS = 'WS_GET_PROFILE_ORDERS';

export const wsGetCommonOrders = () => {
  return {
    type: WS_GET_COMMON_ORDERS
  }
}

export const wsGetProfileOrders = () => {
  return {
    type: WS_GET_PROFILE_ORDERS
  }
}